### ISSUE TITLE
Repo needs some tidying up

### ISSUE THREAD

**Issue by samsalisbury** [opentable/sous#42]
The top-level directory in the repo has things out of place. This wasn't documented, so I'll add the below description as a document now...

Here's a description of what the directories in the top level are for:

- **bin**: standalone scripts and binary utils used to build, test, experiment with sous
- **cli**: the Sous command line interface, using util/cmdr (uses: lib, ext, util)
- **doc**: documentation
- **ext**: libraries talking to external services, e.g. the filesystem, network, shell etc. Packages in ext will typically talk to these services to construct or act upon structures defined in lib.
- **server**: does not exist yet; will be the sous HTTP server library.
- **sous**: (will be renamed to "lib" as per [this suggestion]) sous library providing core sous functionality. MUST NOT reference ext, cli, server.
- **util**: completely standalone, generic utility libraries. MUST NOT reference anything outside of util, vendor. Util libs can be consumed from anywhere else in the code base.
- **vendor**: standard vendor directory.

So, we have a few things out of place:

- **test_with_docker** should be in util
- **exploratory/cert_san** should be in bin
- **exploratory/docker_labels** should be in bin

[this suggestion]: https://peter.bourgon.org/go-best-practices-2016/#repository-structure

**Comment by nyarly** [comment]
I restructured the code according to this, *but:* I've come across a kind of diamond-dependancy issue.

The main sous build.go code needs to reference e.g. the dockerfile buildpack. That sensibly belongs in ext/, since it interacts with docker, but it needs to return (and therefore reference) e.g. BuildResult objects. So either BuildResult, the build code and the buildpack all live in lib/ together, or only the BuildResult lives there, the buildpack(s) live in ext/ and build is its own package.

It's possible that psyringe can solve this, but in general I'm concerned by the degree to which the Go packaging rules (namely, that import is a DAG) perturb the design of the code. It's one thing to say that e.g. basic types are what Sous provides, and that main work happens in ext/ or util/, but that severely limits the kind of methods on those types (effectively to conversions) and leads to manager-type objects - e.g. BuildContext vs. Builder. That might not be a terrible result, but it needs recognition.

**Comment by samsalisbury** [comment]
I'll close this issue, thanks for doing the rearrangement. Re the problems with import being a DAG, I've had a lot of frustration with this in the past, which is one of the reasons I've wanted to be careful with what goes where in the codebase. One single package would work, but would become unmanageably large pretty quickly, so I feel we need to split it out into separate packages.

So, the basic strategy is that the Sous Lib houses all the Sous-specific DTOs and interfaces, and any functionality that can meaningfully be applied to that small set of things, as well as any Sous-specific util functions, e.g. conversions and the like. Yes, this means the Sous package will end up being relatively small and won't do much, but that's by design. Since it _may not reference `ext/...`_ every package in ext is free to reference sous, and to deal in its types, and ext packages may reference each other if it's done without circular dependencies.

Importantly, `util` may not reference anything in `ext` or `sous` as it should be usable from any other package.

So, the `main`, `cli`, and eventually `server` packages should all be free to reference both `ext` and `sous`. Only `main` will ever produce a binary, with a specific command to start the server.

**Comment by samsalisbury** [comment]
I think it would be really easy to build a tool that checks for undesirable references to catch not-already-circular-but-risky dependencies early, probably using either package-level comments or a dotfile...

**Comment by samsalisbury** [comment]
I can't find one, if I get a spare half an hour outside of work I'll write it.
